org.gradle.jvmargs=-Xmx4096m -Dfile.encoding=UTF-8
android.useAndroidX=true
android.enableAapt2=true
kotlin.compiler.execution.strategy=in-process
android.minSdkVersion=24
android.targetSdkVersion=36
android.compileSdkVersion=36
android.minSdkVersion=24
android.targetSdkVersion=36
android.compileSdkVersion=36
